config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :blog_posts
  resources :comments, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy]
  
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
    end
  end
  resources :events, except: [:edit, :update]

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

	def new
	end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

	def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:subject, :body,recipients:[])
  end

  def message_params
    params.require(:message).permit(:body, :subject)
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <br><%= render 'shared/avatar', user: conversation.originator %>
      <%= conversation.originator.name %><small><b> και </b></small>
        <%= conversation.recipients.first.name %>
      <div class="pull-right">
      <small><b>Ημερομηνία: </b><%=  conversation.messages.last.created_at.strftime("%D, %H:%M") %></small></div>
    </h4>
    <h4>Θέμα:</h4> <%= truncate conversation.subject %>
    <%= link_to "Άνοιγμα", conversation_path(conversation)  %>
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :"Παραλήπτες" %>
      <%= f.select(:recipients, current_user.followers.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "form-control" })%>
    </div>
    <div class="form-group">
     	<%= f.label :"Θέμα" %>
     	<%= f.text_field :Subject, placeholder: "Θέμα", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :"Μύνημα" %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Γράψτε το μύνημά σας εδώ....", rows: 4  %>
    </div>

    <%= f.submit "Αποστολή", class: "btn btn-success" %>
    
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <br><%= render 'shared/avatar', user: message.sender %>
          <%= message.sender.name %></br>
          <div class="pull-right">
             <small><b>Ώρα: </b><%=  message.created_at.strftime("%H:%M") %></small></div>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <div class="form-group">
      <%= link_to "Δημιούργησε", new_conversation_path, class: "btn btn-success" %>
    </div>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Επαναφορά', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Διαφραφή', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Απάντηση......", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Απάντηση", class: 'btn btn-success pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>