config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :blog_posts
  resources :comments, only: [:create, :destroy]
  resources :votes, only: [:create, :destroy]
  
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
    end
  end
  resources :events, except: [:edit, :update]

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/concerns/shared/callbacks.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

module Shared::Callbacks
  extend ActiveSupport::Concern

  included do
    before_destroy :remove_activity
  end

  def remove_activity
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.create")
    activity.destroy && remove_likes if activity.present?
    true
  end

  def remove_likes
    activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.to_s, key: "#{self.class.to_s.downcase}.like")
    activity.destroy if activity.present?
 	end
end

app/views/shared/_actions.html.erb
<% if user_signed_in? %>
  <div class="actions">
    <div class="row">
      <div class="col-xs-6 like">
        <%= render 'likes/form', likeable: resource %>
      </div>
      <div class="col-xs-6 comment">
        <%= link_to resource, class: 'btn btn-block' do %>
          <%= fa_icon 'comment' %> Σχολίασε
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_activity.html.erb
<div id="activity-<%= activity.id %>" class="activity">
  <%= render_activity(activity) %>
</div>

app/views/shared/_avatar.html.erb
<%= link_to user_path(user) do %>
  <%= image_tag @user.avatar.url || 'avatar.jpg', class: 'avatar' %>
<% end %>

app/views/shared/_cover.html.erb
<% if user.cover.url %>
  <div class="cover" style="background-image: url(<%= user.cover.url %>);"></div>
<% else %>
  <div class="cover" style="background-image: url(/assets/cover.png);"></div>
<% end %>

app/views/shared/_created_at.html.erb
<div class="created-at">
  <%= fa_icon 'clock-o' %>
  <%= activity.created_at.strftime("%H:%M, %D") %>
</div>

app/views/shared/_links.html.erb
<div id="links" class="well">
  <h5>
    <%= fa_icon 'calendar-o' %>
    <%= link_to 'Δυμιουργία εκδήλωσης', new_event_path %>
  </h5>
  <h5>
    <%= fa_icon 'arrow-circle-right' %>
    <%= link_to 'Φίλοι', friends_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'arrow-circle-left' %>
    <%= link_to 'Ακόλουθοι', followers_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'search' %>
    <%= link_to('Βρες φίλους', find_friends_path)%>
  </h5>
  <h5>
    <%= fa_icon 'pencil' %>
    <%= link_to 'Επεξεργασία προφίλ', edit_user_path(current_user) %>
  </h5>
  <h5>
    <%= fa_icon 'lock' %>
    <%= link_to 'Αλλαγή κωδικού', edit_user_registration_path %>
  </h5>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Teenager", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-top">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Blog", blog_posts_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Αρχική", root_url %></li>
          <li><%= link_to(current_user.name, user_path(current_user)) %></li>
          
          <li><%= link_to mailbox_inbox_path do  %>
            <% if unread_messages_count>0 %>
              <span class="label label-danger pull-right">
                <%=unread_messages_count%>
              </span>
            <% end %>
              <em class="fa fa-inbox fa-lg"></em>
              <span>Μηνύματα</span>
            <% end %>
          </li>

          <li><%= link_to('Αποσύνδεση', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to 'Εγγραφή', new_user_registration_path %></li>
          <li><%= link_to 'Σύνδεση', user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_no_resource.html.erb
<div class="no-resource text-center">
	<h5>No <%= resources %> found.</h5>
</div>

app/views/shared/_paginate.html.erb
<div id="endless-scroll" class="well text-center hidden">
  <%= image_tag 'ajax-loader.gif' %>
  <%= will_paginate resources %>
</div>

app/views/shared/_paginate.js.erb
<% if resources.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(resources) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#endless-scroll").remove();
<% end %>

app/views/shared/_user_info.html.erb
<div id="user-info" class="well">
  <div class="text-center">
    <%= render 'shared/avatar', user: @user %><br>
    <h5><%= link_to @user.name, @user %></h5>
  </div>
  <h5>
    <%= fa_icon 'shield' %>
    <%= pluralize(@user.posts_count, 'post') %>
  </h5>
  <% if @user.birthday.present? %>
    <h5>
      <%= fa_icon @user.sex %>
      <%= "#{pluralize(age(@user.birthday), '')} χρονών" %>
    </h5>
  <% end %>

  <% if @user.school.present? %>
    <h5>
      <%= fa_icon 'graduation-cap' %>
      <%= pluralize(@user.school, '') %>
    </h5>
  <% end %>
  <% if @user.url.present? %>
      <h5>

      <% if @user.sex == "male" %>
        <%= fa_icon 'steam-square' %>
        <%= link_to "steam profile", @user.url, :target => '_blank' %>
      <% else %>
        <%= fa_icon 'heart' %>
        <%= link_to "heartit profile", @user.url, :target => '_blank' %>

      <% end %>
      </h5>
  <% end %>

  <% if @user.location.present? %>
    <h5>
      <%= fa_icon 'map-marker' %>
      <%= @user.location %>
    </h5>
  <% end %>
  <br>
  <div class="text-center">
    <% unless is_current_user?(@user) %>
      <%= render 'follows/form', user: @user %>
      <h6><%= 'Σας ακολουθεί' if current_user.followed_by?(@user) %></h6>
    <% end %>
  </div>
</div>